name        = "Propergol"
name8       = "ppg"
locale      = "fr"
variant     = "Kawa"
author      = "Kawamashi"
description = "Propergol"
url         = "https://OneDeadKey.github.com/kalamine"
version     = "0.0.5"
geometry    = "ERGO"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ ~   ┃ €   │ <   │ > ⅔ │ $ ¾ │ % ‰ ┃ ^ ‚ │ & ‘ │ | ’ │ #   │ @   ┃ * × ┆ \ ≠ ┆
┆ `   ┃ 1 ¢ │ 2 ½ │ 3 ⅓ │ 4 ¼ │ 5 § ┃ 6 ™ │ 7 © │ 8 ∞ │ 9 ¶ │ 0 ° ┃ / ÷ ┆ = ≈ ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ ?   │ É   │ U   │ P   │ !   ┃ V " │ M « │ C » │ J   │ X ¡ ┃ " ⇐ ┆ + ± ┆
·     ┃ , œ │   æ │   û │   ù │ -   ┃   „ │   “ │   ” │   @ │   ‑ ┃ ' ← ┆ - − ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ O   │ A   │ I   │ N   │ : ¿ ┃ G   │ T   │ S   │ R   │ L   ┃ [ ⇒ ┆ ] ⇔ ┆
·     ┃   ô │   â │   î │   à │ . … ┃  *µ │   / │   ç │   € │   £ ┃ _ → ┆ ’ ↔ ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ E   ┃ Q   │ Z   │ Y   │ H   │ B { ┃ K } │ D · │ F   │ W — │ ;   ┃           ·
┆   ê ┃     │   è │   ï │   ñ │   ( ┃   ) │  *¨ │   ß │   – │**   ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃   ¹ │   ² │   ³ │   ⁴ │   ⁵ ┃   ⁶ │   ⁷ │   ⁸ │   ⁹ │   ⁰ ┃     ┆     ┆
┆   … ┃   ₁ │   ₂ │   ₃ │   ₄ │   ₅ ┃   ₆ │   ₇ │   ₈ │   ₉ │   ₀ ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃  *^ │  *˘ │  *˚ │  *¤ │   ‰ ┃     │  *” │   ≠ │   ¬ │  *` ┃     ┆     ┆
·     ┃   ^ │   { │   } │   $ │   % ┃   # │   " │   = │   ! │   ` ┃   è ┆   ê ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃  *ˇ │     │  *¯ │  *˙ │   : ┃  */ │   ÷ │   − │   ± │   × ┃     ┆     ┆
·     ┃   ? │   ( │   ) │   ; │   : ┃   \ │   / │   - │   + │   * ┃   à ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆  *¯ ┃   ≤ │  *, │  *˛ │   ≥ │     ┃     │  *´ │  *¸ │   ¦ │  *~ ┃           ·
┆   _ ┃   < │   [ │   ] │   > │   @ ┃     │   ' │   & │   | │   ~ ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
shift       = "\u202f"  # NARROW NO-BREAK SPACE
altgr       = "\u0020"  # SPACE
altgr_shift = "\u00a0"  # NO-BREAK SPACE
1dk         = "\u005f"  # UNDERSCORE
1dk_shift   = "\u2011"  # NON-BREAKING HYPHEN
